import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai'
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png'
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Shanmukh Magapu Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white text-black px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>DevelopedByShannu</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Shanmukh Magapu</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Full Stack Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200'>
              This is Shanmukh Magapu, I am a certified and professional developer and freelancer.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400 '>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>
        </section>

        {/* Section 2 */}
        <section className="py-16">
  <div className="container mx-auto">
    <h2 className="text-3xl md:text-4xl text-center font-bold text-gray-800 dark:text-gray-200 mb-8">Services I Offer</h2>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
      <div className="bg-white dark:bg-gray-800 shadow-lg rounded-xl p-8">
        <Image src={design} width={100} height={100} className="mx-auto" />
        <h3 className="text-xl font-medium text-center mt-6 mb-4 dark:text-teal-600 font-semibold mb-2">Beautiful Design Architecture</h3>
        <p className="text-gray-700 dark:text-gray-300 text-center mb-4">Creating elegant designs suited for your needs following core design theory.</p>
        <div className="text-center">
          <h4 className="text-teal-600 font-semibold mb-2">Design tools I use</h4>
          <p className="text-gray-800 dark:text-gray-300">Photoshop</p>
          <p className="text-gray-800 dark:text-gray-300">Designing</p>
          <p className="text-gray-800 dark:text-gray-300">Figma</p>
        </div>
      </div>
      <div className="bg-white dark:bg-gray-800 shadow-lg rounded-xl p-8">
        <Image src={code} width={100} height={100} className="mx-auto" />
        <h3 className="text-xl font-medium text-center mt-6 mb-4 dark:text-teal-600 font-semibold mb-2">Organizing and Maintenance</h3>
        <p className="text-gray-700 dark:text-gray-300 text-center mb-4">Creating elegant designs suited for your needs following core design theory.</p>
        <div className="text-center">
          <h4 className="text-teal-600 font-semibold mb-2">Design tools I use</h4>
          <p className="text-gray-800 dark:text-gray-300">Photoshop</p>
          <p className="text-gray-800 dark:text-gray-300">Designing</p>
          <p className="text-gray-800 dark:text-gray-300">Figma</p>
        </div>
      </div>
      <div className="bg-white dark:bg-gray-800 shadow-lg rounded-xl p-8">
        <Image src={consulting} width={100} height={100} className="mx-auto" />
        <h3 className="text-xl font-medium text-center mt-6 mb-4 dark:text-teal-600 font-semibold mb-2">High-level Illustrations</h3>
        <p className="text-gray-700 dark:text-gray-300 text-center mb-4">Creating elegant designs suited for your needs following core design theory.</p>
        <div className="text-center">
          <h4 className="text-teal-600 font-semibold mb-2">Design tools I use</h4>
          <p className="text-gray-800 dark:text-gray-300">Photoshop</p>
          <p className="text-gray-800 dark:text-gray-300">Designing</p>
          <p className="text-gray-800 dark:text-gray-300">Figma</p>
        </div>
      </div>
    </div>
  </div>
</section>


       {/* Section 3 (Portfolio) */}
<section>
  <div>
    <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
    <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
      Here are some of the projects I've worked on as a Full Stack Developer.
    </p>
  </div>
  <div className='flex flex-col gap-10 py-10 md:flex-row md:flex-wrap '>
    <div className='basis-1/3 flex-1 hover:rotate-12 hover:scale-105 transform transition-transform duration-500 ease-in-out'>
      <Image className='rounded-lg object-cover w-full h-full' src={web2} />
    </div>
    <div className='basis-1/3 flex-1 hover:rotate-12 hover:scale-105 transform transition-transform duration-500 ease-in-out'>
      <Image className='rounded-lg object-cover w-full h-full' src={web3} />
    </div>
    <div className='basis-1/3 flex-1 hover:rotate-12 hover:scale-105 transform transition-transform duration-500 ease-in-out'>
      <Image className='rounded-lg object-cover w-full h-full' src={web1} />
    </div>
    <div className='basis-1/3 flex-1 hover:rotate-12 hover:scale-105 transform transition-transform duration-500 ease-in-out'>
      <Image className='rounded-lg object-cover w-full h-full' src={web4} />
    </div>
    <div className='basis-1/3 flex-1 hover:rotate-12 hover:scale-105 transform transition-transform duration-500 ease-in-out'>
      <Image className='rounded-lg object-cover w-full h-full' src={web5} />
    </div>
    <div className='basis-1/3 flex-1 hover:rotate-12 hover:scale-105 transform transition-transform duration-500 ease-in-out'>
      <Image className='rounded-lg object-cover w-full h-full' src={web6} />
    </div>
  </div>
</section>


        {/* Footer */}
        <footer className="py-12 text-center dark:text-white">
          <p>&copy; 2024 Shanmukh Magapu Portfolio. All rights reserved.</p>
        </footer>

      </main>
    </div>
  )
}
